# Generated by Django 3.2 on 2021-07-06 03:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='competencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_competencia', models.IntegerField()),
                ('nombre', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='medio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_medio', models.IntegerField()),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='periodista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=13)),
                ('nombre', models.CharField(max_length=35)),
                ('apellido_paterno', models.CharField(max_length=30)),
                ('apellido_materno', models.CharField(max_length=30)),
                ('correo', models.EmailField(max_length=40)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='tipo_medio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_tipo_medio', models.IntegerField()),
                ('nombre', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='publicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_publicacion', models.IntegerField()),
                ('titulo', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=600)),
                ('idioma', models.CharField(max_length=100)),
                ('fecha_publicacion', models.DateField()),
                ('cod_competencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.competencia')),
                ('rut', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.periodista')),
            ],
        ),
        migrations.CreateModel(
            name='posee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_medio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.medio')),
                ('rut', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.periodista')),
            ],
        ),
        migrations.AddField(
            model_name='medio',
            name='cod_tipo_medio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.tipo_medio'),
        ),
    ]
