# Generated by Django 3.2 on 2021-07-06 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medio',
            old_name='cod_tipo_medio',
            new_name='tipo_medio',
        ),
        migrations.RenameField(
            model_name='posee',
            old_name='cod_medio',
            new_name='medio',
        ),
        migrations.RenameField(
            model_name='posee',
            old_name='rut',
            new_name='periodista',
        ),
        migrations.RenameField(
            model_name='publicacion',
            old_name='cod_competencia',
            new_name='competencia',
        ),
        migrations.RenameField(
            model_name='publicacion',
            old_name='rut',
            new_name='periodista',
        ),
    ]
