# Generated by Django 3.2 on 2021-07-06 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0002_auto_20210706_0046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medio',
            name='tipo_medio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aplicacion.tipo_medio'),
        ),
        migrations.AlterField(
            model_name='posee',
            name='medio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aplicacion.medio'),
        ),
        migrations.AlterField(
            model_name='posee',
            name='periodista',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aplicacion.periodista'),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='competencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aplicacion.competencia'),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='periodista',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aplicacion.periodista'),
        ),
    ]
