# Generated by Django 3.2 on 2021-07-06 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0004_auto_20210706_1612'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='periodista',
            name='id',
        ),
        migrations.AlterField(
            model_name='periodista',
            name='rut',
            field=models.CharField(max_length=13, primary_key=True, serialize=False),
        ),
    ]
